---
- hosts: all
  become: true
  gather_facts: true

  vars:
    password: "{{ lookup('env','TG_BOT_PASSWD') }}"
    token:    "{{ lookup('env','TG_BOT_TOKEN') }}"

  tasks:
    - fail:
        msg: 'Variable {{item}} not defined'
      when: item is not defined
      with_items:
        - password
        - token

    - name: Install dependencies
      apt:
        update_cache: yes
        pkg:
          - git
          - sudo
          - python3-pip

    - name: Git checkout
      git:
        repo: 'https://github.com/sistematico/bento-carneiro.git'
        dest: /var/bentocarneiro/bot
        force: yes

    - name: Ensure group bentocarneiro exists
      group:
        name: bentocarneiro
        state: present

    - name: Create a 2048-bit SSH key for user bentocarneiro in /var/bentocarneiro/.ssh/id_rsa
      user:
        name: bentocarneiro
        shell: /bin/bash
        home: /var/bentocarneiro
        password: "{{ password | password_hash('sha512') }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        state: present

    - name: Install python-telegram-bot python package
      pip:
        name: python-telegram-bot

    - name: Copy bot files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ item.user }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      with_items:
        - { src: "./etc/systemd/system/bentocarneiro.service", dest: "/etc/systemd/system/bentocarneiro.service", user: "root",          group: "root",          mode: "0644" }
        - { src: "./config/config.py.j2",                      dest: "/var/bentocarneiro/bot/config/config.py",   user: "bentocarneiro", group: "bentocarneiro", mode: "0644" }

    - name: Config sudoers file
      community.general.sudoers:
        name: bentocarneiro-service
        user: bentocarneiro
        commands:
          - /usr/bin/systemctl start bentocarneiro
          - /usr/bin/systemctl restart bentocarneiro
          - /usr/bin/systemctl stop bentocarneiro
        nopassword: true

    - name: Chown bot directory
      file:
        dest: /var/bentocarneiro
        owner: bentocarneiro
        group: bentocarneiro
        recurse: yes

    - name: Start systemd service
      systemd:
        name: bentocarneiro
        state: restarted
        daemon_reload: yes
        enabled: yes
